// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"api/infrastructure/rdb"
	"api/infrastructure/repository"
	"api/presentation/user"
	user2 "api/usecase/user"
)

// Injectors from wire.go:

func InitUser() user.Handler {
	db := rdb.NewDB()
	userRepository := repository.NewUserRepository(db)
	findUserUseCase := user2.NewFindUserUseCase(userRepository)
	handler := user.NewHandler(findUserUseCase)
	return handler
}
