version: '3'

dotenv: ['.env']
silent: true

tasks:
  default:
    aliases:
      - list
    desc: List all tasks
    cmd: task -l
  iac-fmt:
    desc: Format terraform files
    cmds:
      - cd terraform && terraform fmt -recursive
  iac-lint:
    desc: Lint terraform files
    cmds:
      - cd terraform && tflint --recursive
  dev-plan:
    desc: Plan terraform for dev
    cmds:
      - cd terraform/envs/dev && terraform plan
  dev-apply:
    desc: Plan terraform for dev
    cmds:
      - cd terraform/envs/dev && terraform apply
  pro-apply:
    desc: Plan terraform for dev
    cmds:
      - cd terraform/envs/pro && terraform apply
  dev-destroy:
    desc: Plan terraform for dev
    cmds:
      - cd terraform/envs/dev && terraform destroy
  pro-destroy:
    desc: Plan terraform for dev
    cmds:
      - cd terraform/envs/pro && terraform destroy