version: "3"

silent: true
dotenv: [".env"]

includes:
  api:
    taskfile: api/Taskfile.api.yaml
    dir: taskfiles

  terraform:
    taskfile: terraform/Taskfile.terraform.yaml
    dir: taskfiles

tasks:
  default:
    aliases:
      - list
    desc: List all tasks
    cmd: task -l
