version: '3'

dotenv: ['.env']

tasks:
  image-push-api:
    cmds:
      - docker build -t my-image .
      - docker tag my-image my-repo/my-image
      - docker push my-repo/my-image
  image-push-log:
    cmds:
      - aws ecr get-login-password --region ap-northeast-1 --profile administrator | docker login --username AWS --password-stdin {{ .AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com
      - cd ../firelens && docker build -t sbcntr-log --platform linux/x86_64 .
      - docker tag sbcntr-log:latest {{ .AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com/sbcntr-log:v1
      - docker push {{ .AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com/sbcntr-log:v1
  fmt:
    cmds:
      - cd terraform && terraform fmt -recursive
  lint:
    cmds:
      - cd terraform && tflint --recursive
  dev-plan:
    cmds:
      - cd terraform/envs/dev && terraform plan
  dev-apply:
    cmds:
      - cd terraform/envs/dev && terraform apply
  pro-apply:
    cmds:
      - cd terraform/envs/pro && terraform apply
  dev-destroy:
    cmds:
      - cd terraform/envs/dev && terraform destroy
  pro-destroy:
    cmds:
      - cd terraform/envs/pro && terraform destroy