version: '3'

dotenv: ['.env']

tasks:
  image-push-api:
    cmds:
      - docker build -t my-image .
      - docker tag my-image my-repo/my-image
      - docker push my-repo/my-image
  image-push-log:
    cmds:
      - docker build -t my-image .
      - docker tag my-image my-repo/my-image
      - docker push my-repo/my-image
  fmt:
    cmds:
      - terraform fmt -recursive
  lint:
    cmds:
      - tflint --recursive
  dev-plan:
    cmds:
      - cd envs/dev && terraform plan
  dev-apply:
    cmds:
      - cd envs/dev && terraform apply
  pro-apply:
    cmds:
      - cd envs/pro && terraform apply
  dev-destroy:
    cmds:
      - cd envs/dev && terraform destroy
  pro-destroy:
    cmds:
      - cd envs/pro && terraform destroy