version: '3'

dotenv: ['.env']

tasks:
  image-push-api:
    cmds:
      - docker build -t my-image .
      - docker tag my-image my-repo/my-image
      - docker push my-repo/my-image
  image-push-log:
    cmds:
      - aws ecr get-login-password --region ap-northeast-1 --profile administrator | docker login --username AWS --password-stdin {{ .AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com
      - cd ../firelens && docker build -t sbcntr-log .
      - docker tag sbcntr-log:latest {{ .AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com/sbcntr-log:latest
      - docker push {{ .AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com/sbcntr-log:latest
  fmt:
    cmds:
      - terraform fmt -recursive
  lint:
    cmds:
      - tflint --recursive
  dev-plan:
    cmds:
      - cd envs/dev && terraform plan
  dev-apply:
    cmds:
      - cd envs/dev && terraform apply
  pro-apply:
    cmds:
      - cd envs/pro && terraform apply
  dev-destroy:
    cmds:
      - cd envs/dev && terraform destroy
  pro-destroy:
    cmds:
      - cd envs/pro && terraform destroy