version: '3'

tasks:
  run-dev:
    cmds:
      - docker-compose up -d
      - go run cmd/main.go
  migrate:
    cmds:
     - migrate create -ext sql -dir infrastructure/migrate -seq create_users_table
  migrate-up:
    cmds:
      - migrate -path infrastructure/migrate -database "user:password@tcp(localhost:3306)/sbcntrapp" -verbose up
  sqlc-gen:
    cmds:
      - sqlc generate
