name: ecr push image

on:
  push:
    branches: ["main"]
  pull_request:

env:
  ECS_CLUSTER: dev-sbcntr-api-cluster
  ECS_SERVICE: dev-sbcntr-api-service
  ECS_TASK_DEFINITION: ./api/deploy/ecs-task-def.json

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: production
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: "ap-northeast-1"
          role-to-assume: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/dev-sbcntr-oidc-role"

      - uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr

      - name: build and push docker image to ecr
        id: build-image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: "sbcntr-api"
          IMAGE_TAG: ${{ github.sha }}
          ENVIRONMENT: ${{ vars.ENV }}
        run: |
          ls -la
          docker build . --tag ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.ENVIRONMENT }}-${{ env.IMAGE_TAG }}
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.ENVIRONMENT }}-${{ env.IMAGE_TAG }}

      - uses: kayac/ecspresso@v2
        with:
          version: v2.3.4
      - run: |
          ecspresso version

      - name: deploy to api
        id: task-def-go
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: sbcntr-api
          image: ${{ steps.build-image.outputs.image }}

      - name: stop auto scaling
        run: |
          ecspresso deploy --suspend-auto-scaling

      - name: Deploy app with CodeDeploy Blue/Green deployment
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def-go.outputs.task-definition }}
          cluster: dev-sbcntr-api-cluster
          service: dev-sbcntr-api-service

      - name: restart auto scaling
        run: |
          ecspresso deploy --resume-auto-scaling
