name: image-push-api
on:
  push:
    branches: ["main", "feature-fix-deploy"]
  workflow_dispatch: {}

env:
  ECS_CLUSTER: dev-sbcntr-api-cluster
  ECS_SERVICE: dev-sbcntr-api-service
  ECS_TASK_DEFINITION: ./api/deploy/ecs-task-def.json

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: pro
    defaults:
      run:
        working-directory: ./api
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: "ap-northeast-1"
          role-to-assume: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/dev-sbcntr-oidc-role"

      - uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr

      - name: Build and push
        uses: docker/build-push-action@v3
        id: build-image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: "sbcntr-api"
          IMAGE_TAG: ${{ github.sha }}
          ENVIRONMENT: "dev"
        with:
          file: ./api/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.ENVIRONMENT }}-${{ env.IMAGE_TAG }}

      - name: describe task definition
        run: |
          aws ecs describe-task-definition \
           --task-definition sbcntr-backend-def  \
           --query taskDefinition > api/deploy/ecs-task-def.json
